[tool.poetry]
name = "academlogen9"
version = "0.0.1"
description = ""
authors = ["Nicolas <nicolas.rondon@academlo.com>"]
readme = "README.md"
[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
Jinja2= "^3.0.3"
parse="^1.19.0"
requests="2.27.1"
requests-wsgi-adapter="0.4.1"
WebOb="1.8.7"
whitenoise="6.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
