[tool.poetry]
name = "asciii"
version = "1.0.13"
description = "A library that converts images to ascii"
authors = ["acup1 <georgiyegoriy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
Pillow = "^9.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
