############
### Configuration of the project
############

[tool.poetry]
name = "leximpact_socio_fisca_simu_etat"
version = "0.1.1"
description = "_HTTP + WebSocket API for OpenFisca"
license = "AGPL-3.0-or-later"
authors = ["Leximpact <Leximpact@an.fr>"]
readme = "README.md"
homepage = "https://simulateur-socio-fisca.leximpact.dev/"
repository = "https://git.leximpact.dev/leximpact/leximpact-socio-fiscal-api/"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.4"
OpenFisca-France = "=113.0.3"  # Doit correspondre Ã  openfisca-france-reforms
tables = ">=3.6.1"
toolz = ">=0.11.1"
# python-dotenv = ">=0.18.0"
redis = "^3.5.3"

####
# Following packages are not needed in PyPi package
fastapi = "^0.63.0"
uvicorn = {extras = ["standard"], version = "^0.13.4"}
prometheus-fastapi-instrumentator = "^5.7.1"
# python-jose is for JWT
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
gunicorn = "^20.1.0"
# openfisca-france-reforms = {git = "https://git.leximpact.dev/openfisca/openfisca-france-reforms.git", tag='1.0.80'}
openfisca-france-reforms = "=1.0.82"
python-decouple = "^3.5"
# memory-profiler = "^0.58.0"
"ruamel.yaml" = "^0.17.21"
# toolz = ">=0.11.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.9.0"
black = ">=21.5b1"
nbdev = "^1.1.14"
pre-commit = "^2.13.0"
nbqa = ">=0.9.0"
seaborn = ">=0.11.1"
papermill = "^2.3.3"
vaex-core = "^4"
locust = "^2.2.3"
# To send to PyPi
twine = "^3.5.0"


[tool.poetry.scripts]
api = "leximpact_socio_fisca_simu_etat_api.server:start_dev"

[tool.poetry2conda]
name = "leximpact_socio_fisca_simu_etat_api-conda-env"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3
